create or replace trigger restricciones_emp
BEFORE INSERT OR UPDATE OF SALARY ON EMPLOYEES
FOR EACH ROW
DECLARE
    NEGATIVO EXCEPTION;
    MAYOR_ANTIGUO EXCEPTION;
    COMISION EXCEPTION;
    
BEGIN
    IF INSERTING AND :NEW.SALARY <0 THEN
    RAISE NEGATIVO;
    ELSIF UPDATING THEN
        IF :OLD.SALARY > :NEW.SALARY THEN
        RAISE MAYOR_ANTIGUO;
        END IF;
        IF :OLD.COMMISSION_PCT IS NULL THEN
        RAISE COMISION;
        END IF;
    END IF;
EXCEPTION 
    WHEN NEGATIVO THEN
    RAISE_APPLICATION_ERROR(-20001,'SALARIO TIENE QUE SER POSITIVO');
    WHEN MAYOR_ANTIGUO THEN
    RAISE_APPLICATION_ERROR(-20002,'MAYOR QUE anterior');
    WHEN COMISION THEN
    RAISE_APPLICATION_ERROR(-20003,'tiene que haber comision');
END;
