CREATE OR REPLACE TRIGGER NOMBRE_DEPARTAMENTO_NOTNULL

BEFORE INSERT ON DEPARTMENTS
FOR EACH ROW
BEGIN
    IF :NEW.DEPARTMENT_NAME IS NULL THEN
    RAISE_APPLICATION_ERROR(-20001,'ERROR: NOMBRE DEP NO PUEDE SER NULO');
    END IF;
END;   

INSERT INTO departments VALUES(100,NULL, 1, 1);